title: Oreoluwa Ogunkola # your name (or website title) here
logo: "/images/_eLU0061.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with an interest in data science. 
  <br><br>
  I am passionate about helping businesses glean insight from data. 
  <br><br>
  <a href="https://www.linkedin.com/in/oreogunkolaxander">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
